export const AUTO_CARRIER_REGISTRY = {
  state_farm_auto: {
    carrier_key: "state_farm_auto",
    display_name: "State Farm Auto",
    institution_type: "auto_insurance_carrier",
    known_portal_urls: ["statefarm.com"],
    known_declarations_labels: ["declarations", "auto policy", "coverage summary"],
    known_liability_labels: ["bodily injury", "property damage"],
    known_deductible_labels: ["collision deductible", "comprehensive deductible"],
    known_vehicle_schedule_labels: ["vehicle schedule", "covered autos"],
    notes: "Starter State Farm auto profile.",
  },
  geico: {
    carrier_key: "geico",
    display_name: "GEICO",
    institution_type: "auto_insurance_carrier",
    known_portal_urls: ["geico.com"],
    known_declarations_labels: ["policy declarations", "coverage information"],
    known_liability_labels: ["bodily injury liability", "property damage liability"],
    known_deductible_labels: ["deductible", "collision", "comprehensive"],
    known_vehicle_schedule_labels: ["vehicle information", "covered vehicle"],
    notes: "Starter GEICO auto profile.",
  },
  progressive_auto: {
    carrier_key: "progressive_auto",
    display_name: "Progressive Auto",
    institution_type: "auto_insurance_carrier",
    known_portal_urls: ["progressive.com"],
    known_declarations_labels: ["declarations page", "policy info"],
    known_liability_labels: ["liability", "uninsured motorist"],
    known_deductible_labels: ["collision deductible", "comp deductible"],
    known_vehicle_schedule_labels: ["vehicle schedule", "vehicles on policy"],
    notes: "Starter Progressive auto profile.",
  },
  allstate_auto: {
    carrier_key: "allstate_auto",
    display_name: "Allstate Auto",
    institution_type: "auto_insurance_carrier",
    known_portal_urls: ["allstate.com"],
    known_declarations_labels: ["declarations", "coverage detail"],
    known_liability_labels: ["bodily injury", "property damage"],
    known_deductible_labels: ["deductible"],
    known_vehicle_schedule_labels: ["vehicle", "auto schedule"],
    notes: "Starter Allstate auto profile.",
  },
  farmers_auto: {
    carrier_key: "farmers_auto",
    display_name: "Farmers Auto",
    institution_type: "auto_insurance_carrier",
    known_portal_urls: ["farmers.com"],
    known_declarations_labels: ["auto declarations", "coverage summary"],
    known_liability_labels: ["liability coverage"],
    known_deductible_labels: ["collision deductible", "other than collision deductible"],
    known_vehicle_schedule_labels: ["covered autos", "vehicle schedule"],
    notes: "Starter Farmers auto profile.",
  },
  liberty_mutual_auto: {
    carrier_key: "liberty_mutual_auto",
    display_name: "Liberty Mutual Auto",
    institution_type: "auto_insurance_carrier",
    known_portal_urls: ["libertymutual.com"],
    known_declarations_labels: ["declarations", "policy summary"],
    known_liability_labels: ["liability", "uninsured motorist"],
    known_deductible_labels: ["deductible"],
    known_vehicle_schedule_labels: ["vehicle information"],
    notes: "Starter Liberty Mutual auto profile.",
  },
  nationwide_auto: {
    carrier_key: "nationwide_auto",
    display_name: "Nationwide Auto",
    institution_type: "auto_insurance_carrier",
    known_portal_urls: ["nationwide.com"],
    known_declarations_labels: ["declarations", "coverage detail"],
    known_liability_labels: ["bodily injury", "property damage"],
    known_deductible_labels: ["collision deductible", "comprehensive deductible"],
    known_vehicle_schedule_labels: ["vehicle schedule"],
    notes: "Starter Nationwide auto profile.",
  },
  usaa_auto: {
    carrier_key: "usaa_auto",
    display_name: "USAA Auto",
    institution_type: "auto_insurance_carrier",
    known_portal_urls: ["usaa.com"],
    known_declarations_labels: ["declarations", "proof of insurance"],
    known_liability_labels: ["liability", "uninsured motorist"],
    known_deductible_labels: ["deductible"],
    known_vehicle_schedule_labels: ["vehicle", "covered auto"],
    notes: "Starter USAA auto profile.",
  },
  aaa_auto: {
    carrier_key: "aaa_auto",
    display_name: "AAA Auto",
    institution_type: "auto_insurance_carrier",
    known_portal_urls: ["aaa.com"],
    known_declarations_labels: ["auto declarations", "policy documents"],
    known_liability_labels: ["bodily injury", "property damage"],
    known_deductible_labels: ["deductible"],
    known_vehicle_schedule_labels: ["vehicle schedule"],
    notes: "Starter AAA auto profile.",
  },
  mercury_auto: {
    carrier_key: "mercury_auto",
    display_name: "Mercury Auto",
    institution_type: "auto_insurance_carrier",
    known_portal_urls: ["mercuryinsurance.com"],
    known_declarations_labels: ["declarations", "policy information"],
    known_liability_labels: ["liability"],
    known_deductible_labels: ["deductible"],
    known_vehicle_schedule_labels: ["vehicle"],
    notes: "Starter Mercury auto profile.",
  },
  travelers_auto: {
    carrier_key: "travelers_auto",
    display_name: "Travelers Auto",
    institution_type: "auto_insurance_carrier",
    known_portal_urls: ["travelers.com"],
    known_declarations_labels: ["declarations", "coverage summary"],
    known_liability_labels: ["liability", "property damage"],
    known_deductible_labels: ["deductible"],
    known_vehicle_schedule_labels: ["vehicle schedule"],
    notes: "Starter Travelers auto profile.",
  },
  carrier_generic_auto: {
    carrier_key: "carrier_generic_auto",
    display_name: "Generic Auto Carrier",
    institution_type: "auto_insurance_carrier",
    known_portal_urls: [],
    known_declarations_labels: ["declarations", "policy summary"],
    known_liability_labels: ["liability"],
    known_deductible_labels: ["deductible"],
    known_vehicle_schedule_labels: ["vehicle schedule", "covered vehicles"],
    notes: "Fallback profile for unknown or regional auto carriers.",
  },
};

export const AUTO_CARRIER_KEYS = Object.freeze(Object.keys(AUTO_CARRIER_REGISTRY));

export function listAutoCarriers() {
  return Object.values(AUTO_CARRIER_REGISTRY);
}

export function getAutoCarrier(carrierKey) {
  return AUTO_CARRIER_REGISTRY[carrierKey] || null;
}
