export const AUTO_POLICY_TYPE_REGISTRY = {
  personal_auto_policy: {
    auto_policy_type_key: "personal_auto_policy",
    display_name: "Personal Auto Policy",
    major_category: "personal_auto",
    liability_relevant: true,
    physical_damage_relevant: true,
    deductible_relevant: true,
    multi_vehicle_possible: true,
    commercial_reference: false,
    rideshare_reference: false,
    uninsured_motorist_relevant: true,
    common_document_labels: ["declarations page", "auto policy", "coverage summary"],
    common_fields_expected: ["bodily_injury_per_person", "property_damage_liability", "collision_deductible", "premium_amount"],
  },
  multi_vehicle_auto_policy: {
    auto_policy_type_key: "multi_vehicle_auto_policy",
    display_name: "Multi-Vehicle Auto Policy",
    major_category: "personal_auto",
    liability_relevant: true,
    physical_damage_relevant: true,
    deductible_relevant: true,
    multi_vehicle_possible: true,
    commercial_reference: false,
    rideshare_reference: false,
    uninsured_motorist_relevant: true,
    common_document_labels: ["vehicle schedule", "multi-car policy", "declarations"],
    common_fields_expected: ["vehicle_count", "multi_vehicle_indicator", "collision_deductible", "comprehensive_deductible"],
  },
  single_vehicle_auto_policy: {
    auto_policy_type_key: "single_vehicle_auto_policy",
    display_name: "Single-Vehicle Auto Policy",
    major_category: "personal_auto",
    liability_relevant: true,
    physical_damage_relevant: true,
    deductible_relevant: true,
    multi_vehicle_possible: false,
    commercial_reference: false,
    rideshare_reference: false,
    uninsured_motorist_relevant: true,
    common_document_labels: ["single vehicle", "proof of insurance", "declarations"],
    common_fields_expected: ["vehicle_count", "year_make_model_summary", "bodily_injury_per_person", "premium_amount"],
  },
  commercial_auto_reference: {
    auto_policy_type_key: "commercial_auto_reference",
    display_name: "Commercial Auto Reference",
    major_category: "commercial_auto",
    liability_relevant: true,
    physical_damage_relevant: true,
    deductible_relevant: true,
    multi_vehicle_possible: true,
    commercial_reference: true,
    rideshare_reference: false,
    uninsured_motorist_relevant: true,
    common_document_labels: ["commercial auto", "business auto policy"],
    common_fields_expected: ["vehicle_count", "named_insured", "property_damage_liability", "policy_status"],
  },
  rideshare_endorsement_reference: {
    auto_policy_type_key: "rideshare_endorsement_reference",
    display_name: "Rideshare Endorsement Reference",
    major_category: "endorsement_reference",
    liability_relevant: true,
    physical_damage_relevant: true,
    deductible_relevant: true,
    multi_vehicle_possible: false,
    commercial_reference: false,
    rideshare_reference: true,
    uninsured_motorist_relevant: true,
    common_document_labels: ["rideshare endorsement", "transportation network coverage"],
    common_fields_expected: ["endorsement_present", "policy_status", "vehicle_count", "premium_amount"],
  },
  motorcycle_policy_reference: {
    auto_policy_type_key: "motorcycle_policy_reference",
    display_name: "Motorcycle Policy Reference",
    major_category: "specialty_vehicle",
    liability_relevant: true,
    physical_damage_relevant: true,
    deductible_relevant: true,
    multi_vehicle_possible: true,
    commercial_reference: false,
    rideshare_reference: false,
    uninsured_motorist_relevant: true,
    common_document_labels: ["motorcycle policy", "bike coverage"],
    common_fields_expected: ["vehicle_count", "collision_deductible", "comprehensive_deductible", "premium_amount"],
  },
  classic_car_policy_reference: {
    auto_policy_type_key: "classic_car_policy_reference",
    display_name: "Classic Car Policy Reference",
    major_category: "specialty_vehicle",
    liability_relevant: true,
    physical_damage_relevant: true,
    deductible_relevant: true,
    multi_vehicle_possible: true,
    commercial_reference: false,
    rideshare_reference: false,
    uninsured_motorist_relevant: true,
    common_document_labels: ["classic car", "collector auto"],
    common_fields_expected: ["year_make_model_summary", "agreed_value_reference", "premium_amount", "policy_status"],
  },
  umbrella_auto_related_reference: {
    auto_policy_type_key: "umbrella_auto_related_reference",
    display_name: "Umbrella Auto-Related Reference",
    major_category: "liability_extension",
    liability_relevant: true,
    physical_damage_relevant: false,
    deductible_relevant: false,
    multi_vehicle_possible: true,
    commercial_reference: false,
    rideshare_reference: false,
    uninsured_motorist_relevant: false,
    common_document_labels: ["umbrella", "excess liability"],
    common_fields_expected: ["bodily_injury_per_person", "property_damage_liability", "policy_status"],
  },
  auto_policy_generic: {
    auto_policy_type_key: "auto_policy_generic",
    display_name: "Auto Policy",
    major_category: "generic_auto",
    liability_relevant: true,
    physical_damage_relevant: true,
    deductible_relevant: true,
    multi_vehicle_possible: true,
    commercial_reference: false,
    rideshare_reference: false,
    uninsured_motorist_relevant: true,
    common_document_labels: ["auto insurance", "declarations", "id card"],
    common_fields_expected: ["named_insured", "effective_date", "expiration_date", "premium_amount"],
  },
};

export const AUTO_POLICY_TYPE_KEYS = Object.freeze(Object.keys(AUTO_POLICY_TYPE_REGISTRY));

export function listAutoPolicyTypes() {
  return Object.values(AUTO_POLICY_TYPE_REGISTRY);
}

export function getAutoPolicyType(policyTypeKey) {
  return AUTO_POLICY_TYPE_REGISTRY[policyTypeKey] || null;
}
