export const LIFE_POLICY_TYPE_CONFIGS = Object.freeze({
  iul: {
    key: "iul",
    label: "Indexed Universal Life",
    aliases: ["indexed universal life", "iul", "index universal life", "indexed ul"],
    keyFields: [
      "accumulation_value",
      "cash_surrender_value",
      "cost_of_insurance",
      "index_strategy",
      "participation_rate",
      "cap_rate",
      "spread",
    ],
    likelyLabels: ["indexed universal life", "index strategy", "participation rate", "cap rate", "spread"],
    interpretationAreas: ["performance", "charges", "loans", "strategy", "illustration_variance"],
    assistantQuestions: [
      "What kind of policy is this?",
      "Is this policy healthy?",
      "What should I review first?",
      "Is the data complete enough to trust?",
      "Is this policy performing well?",
      "Are we ahead or behind the illustration?",
      "Are charges hurting this policy?",
      "Is the policy being funded strongly enough?",
      "Is there visible lapse or loan pressure?",
      "What is the current strategy mix?",
    ],
  },
  ul: {
    key: "ul",
    label: "Universal Life",
    aliases: ["universal life", "ul", "guaranteed universal life", "gul"],
    keyFields: [
      "cash_value",
      "cash_surrender_value",
      "cost_of_insurance",
      "admin_fee",
      "loan_balance",
    ],
    likelyLabels: ["universal life", "monthly deduction", "cost of insurance", "cash surrender value"],
    interpretationAreas: ["performance", "charges", "loans", "funding"],
    assistantQuestions: [
      "What kind of policy is this?",
      "Is this policy healthy?",
      "What should I review first?",
      "Is the data complete enough to trust?",
      "Is cash value growing well?",
      "What charges are hurting it?",
      "Are loans creating risk?",
    ],
  },
  vul: {
    key: "vul",
    label: "Variable Universal Life",
    aliases: ["variable universal life", "vul", "variable life", "separate account", "subaccount"],
    keyFields: [
      "accumulation_value",
      "cash_surrender_value",
      "fixed_account_value",
      "loan_balance",
      "cost_of_insurance",
    ],
    likelyLabels: ["variable universal life", "variable life", "separate account", "subaccount", "fund allocation"],
    interpretationAreas: ["market_exposure", "allocation_visibility", "charges", "loans"],
    assistantQuestions: [
      "What kind of policy is this?",
      "Is this policy healthy?",
      "What should I review first?",
      "Is the data complete enough to trust?",
      "How exposed is this policy to market performance?",
      "Is allocation detail visible?",
      "Are charges or loans creating risk?",
    ],
  },
  whole_life: {
    key: "whole_life",
    label: "Whole Life",
    aliases: ["whole life", "ordinary life", "paid up additions", "dividend option"],
    keyFields: [
      "cash_value",
      "cash_surrender_value",
      "loan_balance",
      "dividend_option",
      "paid_up_additions",
    ],
    likelyLabels: ["whole life", "dividend", "paid up additions", "guaranteed cash value"],
    interpretationAreas: ["cash_value", "dividends", "loans", "guarantees"],
    assistantQuestions: [
      "What kind of policy is this?",
      "Is this policy healthy?",
      "What should I review first?",
      "Is the data complete enough to trust?",
      "Are dividends visible?",
      "Is cash value progressing steadily?",
      "Is there loan pressure?",
    ],
  },
  term: {
    key: "term",
    label: "Term Life",
    aliases: ["term life", "level term", "year term", "term insurance", "conversion option"],
    keyFields: ["death_benefit", "planned_premium", "issue_date", "term_end_date", "conversion_option"],
    likelyLabels: ["term life", "level term", "term expires", "conversion option", "renewal premium"],
    interpretationAreas: ["coverage_duration", "conversion", "renewal"],
    assistantQuestions: [
      "What kind of policy is this?",
      "Is this policy healthy?",
      "What should I review first?",
      "Is the data complete enough to trust?",
      "When does this coverage end?",
      "Is there conversion visibility?",
      "What happens near term expiration?",
    ],
  },
  final_expense: {
    key: "final_expense",
    label: "Final Expense",
    aliases: ["final expense", "burial", "funeral", "simplified issue", "graded benefit"],
    keyFields: ["death_benefit", "planned_premium", "waiting_period", "graded_benefit"],
    likelyLabels: ["final expense", "burial insurance", "graded benefit", "waiting period"],
    interpretationAreas: ["benefit_structure", "waiting_period", "premium_fit"],
    assistantQuestions: [
      "What kind of policy is this?",
      "Is this policy healthy?",
      "What should I review first?",
      "Is the data complete enough to trust?",
      "Is there a waiting period?",
      "What is the benefit structure?",
      "Is this permanent coverage?",
    ],
  },
  unknown: {
    key: "unknown",
    label: "Life Insurance Policy",
    aliases: [],
    keyFields: ["carrier_name", "product_name", "policy_type", "death_benefit", "planned_premium"],
    likelyLabels: [],
    interpretationAreas: ["identity", "coverage", "data_completeness"],
    assistantQuestions: [
      "What kind of policy is this?",
      "Is this policy healthy?",
      "What should I review first?",
      "Is the data complete enough to trust?",
      "Are there any risk flags?",
    ],
  },
});
