const PROPERTY_TYPE_DEFINITIONS = [
  {
    property_type_key: "primary_residence",
    display_name: "Primary Residence",
    major_category: "owner_occupied",
    occupancy_relevant: true,
    mortgage_relevant: true,
    homeowners_relevant: true,
    assessment_relevant: true,
    tax_relevant: true,
    hoa_relevant: true,
    investment_property_relevant: false,
    common_document_labels: ["Deed", "Property Tax Bill", "Assessment Notice", "Closing Statement"],
    common_fields_expected: ["property_address", "owner_name", "purchase_date", "property_tax_amount"],
  },
  {
    property_type_key: "investment_property",
    display_name: "Investment Property",
    major_category: "investment",
    occupancy_relevant: true,
    mortgage_relevant: true,
    homeowners_relevant: true,
    assessment_relevant: true,
    tax_relevant: true,
    hoa_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["Lease", "Tax Bill", "Deed", "Appraisal"],
    common_fields_expected: ["property_address", "rental_indicator", "property_tax_amount", "estimated_market_value"],
  },
  {
    property_type_key: "second_home",
    display_name: "Second Home",
    major_category: "secondary_use",
    occupancy_relevant: true,
    mortgage_relevant: true,
    homeowners_relevant: true,
    assessment_relevant: true,
    tax_relevant: true,
    hoa_relevant: true,
    investment_property_relevant: false,
    common_document_labels: ["Property Tax Bill", "Homeowners Policy", "Deed"],
    common_fields_expected: ["property_address", "owner_name", "property_tax_amount", "hoa_present"],
  },
  {
    property_type_key: "vacation_property",
    display_name: "Vacation Property",
    major_category: "secondary_use",
    occupancy_relevant: true,
    mortgage_relevant: true,
    homeowners_relevant: true,
    assessment_relevant: true,
    tax_relevant: true,
    hoa_relevant: true,
    investment_property_relevant: false,
    common_document_labels: ["Tax Assessment", "HOA Statement", "Property Inspection"],
    common_fields_expected: ["property_address", "occupancy_type", "hoa_amount", "estimated_market_value"],
  },
  {
    property_type_key: "condo_unit",
    display_name: "Condo Unit",
    major_category: "attached_residential",
    occupancy_relevant: true,
    mortgage_relevant: true,
    homeowners_relevant: true,
    assessment_relevant: true,
    tax_relevant: true,
    hoa_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["HOA Statement", "Condo Declaration", "Assessment Notice"],
    common_fields_expected: ["property_address", "hoa_present", "hoa_amount", "occupancy_type"],
  },
  {
    property_type_key: "townhome_property",
    display_name: "Townhome Property",
    major_category: "attached_residential",
    occupancy_relevant: true,
    mortgage_relevant: true,
    homeowners_relevant: true,
    assessment_relevant: true,
    tax_relevant: true,
    hoa_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["Tax Bill", "HOA Notice", "Deed"],
    common_fields_expected: ["property_address", "owner_name", "hoa_present", "property_tax_amount"],
  },
  {
    property_type_key: "multifamily_property",
    display_name: "Multifamily Property",
    major_category: "income_property",
    occupancy_relevant: true,
    mortgage_relevant: true,
    homeowners_relevant: true,
    assessment_relevant: true,
    tax_relevant: true,
    hoa_relevant: false,
    investment_property_relevant: true,
    common_document_labels: ["Lease", "Tax Bill", "Appraisal", "Inspection Report"],
    common_fields_expected: ["property_address", "unit_count", "rental_indicator", "estimated_market_value"],
  },
  {
    property_type_key: "vacant_land",
    display_name: "Vacant Land",
    major_category: "land",
    occupancy_relevant: false,
    mortgage_relevant: true,
    homeowners_relevant: false,
    assessment_relevant: true,
    tax_relevant: true,
    hoa_relevant: false,
    investment_property_relevant: true,
    common_document_labels: ["County Record", "Tax Assessment", "Purchase Closing"],
    common_fields_expected: ["property_address", "parcel_or_apn_masked", "assessed_value", "purchase_date"],
  },
  {
    property_type_key: "rental_property_generic",
    display_name: "Rental Property",
    major_category: "investment",
    occupancy_relevant: true,
    mortgage_relevant: true,
    homeowners_relevant: true,
    assessment_relevant: true,
    tax_relevant: true,
    hoa_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["Lease", "Tax Bill", "HOA Statement"],
    common_fields_expected: ["property_address", "tenant_reference_present", "property_tax_amount", "rental_indicator"],
  },
  {
    property_type_key: "property_generic",
    display_name: "Property",
    major_category: "general",
    occupancy_relevant: true,
    mortgage_relevant: true,
    homeowners_relevant: true,
    assessment_relevant: true,
    tax_relevant: true,
    hoa_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["Deed", "Property Record", "Tax Notice"],
    common_fields_expected: ["property_address", "owner_name", "property_status", "assessed_value"],
  },
];

export const PROPERTY_TYPE_REGISTRY = PROPERTY_TYPE_DEFINITIONS.reduce((accumulator, type) => {
  accumulator[type.property_type_key] = type;
  return accumulator;
}, {});

export const PROPERTY_TYPE_KEYS = PROPERTY_TYPE_DEFINITIONS.map((type) => type.property_type_key);

export function listPropertyTypes() {
  return PROPERTY_TYPE_DEFINITIONS;
}

export function getPropertyType(propertyTypeKey) {
  return PROPERTY_TYPE_REGISTRY[propertyTypeKey] || null;
}
