export const HOMEOWNERS_CARRIER_REGISTRY = {
  state_farm: {
    carrier_key: "state_farm",
    display_name: "State Farm",
    institution_type: "homeowners_carrier",
    known_portal_urls: ["https://www.statefarm.com"],
    known_document_patterns: ["state farm", "homeowners declarations", "renewal certificate"],
    known_declarations_labels: ["declarations", "coverage a", "policy information"],
    known_deductible_labels: ["deductible", "all peril deductible", "wind/hail deductible"],
    known_coverage_labels: ["coverage a", "coverage b", "liability", "medical payments"],
    notes: "Starter carrier profile for standard homeowners and condo policies.",
  },
  farmers: {
    carrier_key: "farmers",
    display_name: "Farmers",
    institution_type: "homeowners_carrier",
    known_portal_urls: ["https://www.farmers.com"],
    known_document_patterns: ["farmers", "home declarations"],
    known_declarations_labels: ["policy declarations", "residence premises"],
    known_deductible_labels: ["deductible", "wind/hail"],
    known_coverage_labels: ["dwelling", "personal property", "loss of use"],
    notes: "Common personal-lines carrier with declarations packet patterns.",
  },
  allstate: {
    carrier_key: "allstate",
    display_name: "Allstate",
    institution_type: "homeowners_carrier",
    known_portal_urls: ["https://www.allstate.com"],
    known_document_patterns: ["allstate", "policy declarations"],
    known_declarations_labels: ["declarations page", "named insured"],
    known_deductible_labels: ["policy deductible", "storm deductible"],
    known_coverage_labels: ["dwelling protection", "liability protection"],
    notes: "Starter profile for declarations and renewal packets.",
  },
  liberty_mutual: {
    carrier_key: "liberty_mutual",
    display_name: "Liberty Mutual",
    institution_type: "homeowners_carrier",
    known_portal_urls: ["https://www.libertymutual.com"],
    known_document_patterns: ["liberty mutual", "home policy"],
    known_declarations_labels: ["declarations", "property insured"],
    known_deductible_labels: ["all peril", "hurricane deductible"],
    known_coverage_labels: ["dwelling coverage", "personal liability"],
    notes: "Starter pattern support only.",
  },
  travelers: {
    carrier_key: "travelers",
    display_name: "Travelers",
    institution_type: "homeowners_carrier",
    known_portal_urls: ["https://www.travelers.com"],
    known_document_patterns: ["travelers", "policy declarations"],
    known_declarations_labels: ["declarations", "residence premises"],
    known_deductible_labels: ["deductible", "wind/hail deductible"],
    known_coverage_labels: ["coverage a dwelling", "coverage e liability"],
    notes: "Useful for declarations and endorsement notices.",
  },
  nationwide: {
    carrier_key: "nationwide",
    display_name: "Nationwide",
    institution_type: "homeowners_carrier",
    known_portal_urls: ["https://www.nationwide.com"],
    known_document_patterns: ["nationwide", "homeowner policy"],
    known_declarations_labels: ["policy declarations", "insured location"],
    known_deductible_labels: ["deductible", "hurricane deductible"],
    known_coverage_labels: ["dwelling", "other structures", "liability"],
    notes: "Shared brand with retirement but separate homeowners registry entry.",
  },
  usaa: {
    carrier_key: "usaa",
    display_name: "USAA",
    institution_type: "homeowners_carrier",
    known_portal_urls: ["https://www.usaa.com"],
    known_document_patterns: ["usaa", "homeowners declarations"],
    known_declarations_labels: ["declarations", "insured property"],
    known_deductible_labels: ["deductible", "windstorm deductible"],
    known_coverage_labels: ["dwelling", "personal property", "liability"],
    notes: "Military household carrier starter profile.",
  },
  aaa: {
    carrier_key: "aaa",
    display_name: "AAA",
    institution_type: "homeowners_carrier",
    known_portal_urls: ["https://www.aaa.com"],
    known_document_patterns: ["aaa", "home policy"],
    known_declarations_labels: ["declarations page", "insured property"],
    known_deductible_labels: ["deductible"],
    known_coverage_labels: ["dwelling coverage", "liability coverage"],
    notes: "Regional variability expected.",
  },
  progressive_home: {
    carrier_key: "progressive_home",
    display_name: "Progressive Home",
    institution_type: "homeowners_carrier",
    known_portal_urls: ["https://www.progressive.com"],
    known_document_patterns: ["progressive home", "homeowners declarations"],
    known_declarations_labels: ["policy summary", "declarations"],
    known_deductible_labels: ["policy deductible"],
    known_coverage_labels: ["dwelling", "personal property", "liability"],
    notes: "May bridge to partner underwriters.",
  },
  mercury: {
    carrier_key: "mercury",
    display_name: "Mercury",
    institution_type: "homeowners_carrier",
    known_portal_urls: ["https://www.mercuryinsurance.com"],
    known_document_patterns: ["mercury", "property policy"],
    known_declarations_labels: ["declarations", "location address"],
    known_deductible_labels: ["all peril deductible"],
    known_coverage_labels: ["dwelling", "loss of use"],
    notes: "Starter declarations support.",
  },
  geico_home_reference: {
    carrier_key: "geico_home_reference",
    display_name: "GEICO Home Reference",
    institution_type: "homeowners_carrier_reference",
    known_portal_urls: ["https://www.geico.com"],
    known_document_patterns: ["geico", "homeowners reference"],
    known_declarations_labels: ["homeowners declarations"],
    known_deductible_labels: ["deductible"],
    known_coverage_labels: ["dwelling", "liability"],
    notes: "Reference entry because underwriting may be delegated.",
  },
  lemonade: {
    carrier_key: "lemonade",
    display_name: "Lemonade",
    institution_type: "homeowners_carrier",
    known_portal_urls: ["https://www.lemonade.com"],
    known_document_patterns: ["lemonade", "policy declarations"],
    known_declarations_labels: ["policy details", "insured address"],
    known_deductible_labels: ["deductible"],
    known_coverage_labels: ["coverage limits", "personal property"],
    notes: "Digital-first carrier starter profile.",
  },
  hippo: {
    carrier_key: "hippo",
    display_name: "Hippo",
    institution_type: "homeowners_carrier",
    known_portal_urls: ["https://www.hippo.com"],
    known_document_patterns: ["hippo", "home policy"],
    known_declarations_labels: ["declarations", "insured property"],
    known_deductible_labels: ["deductible", "wind/hail deductible"],
    known_coverage_labels: ["dwelling coverage", "service line"],
    notes: "Modern homeowners carrier starter profile.",
  },
  carrier_generic_homeowners: {
    carrier_key: "carrier_generic_homeowners",
    display_name: "Generic Homeowners Carrier",
    institution_type: "homeowners_carrier",
    known_portal_urls: [],
    known_document_patterns: ["declarations", "renewal packet", "homeowners policy"],
    known_declarations_labels: ["named insured", "property address"],
    known_deductible_labels: ["deductible"],
    known_coverage_labels: ["dwelling", "personal property", "liability"],
    notes: "Fallback reference for unknown carriers until parser support exists.",
  },
};

export const HOMEOWNERS_CARRIER_KEYS = Object.freeze(
  Object.keys(HOMEOWNERS_CARRIER_REGISTRY)
);

export function listHomeownersCarriers() {
  return Object.values(HOMEOWNERS_CARRIER_REGISTRY);
}

export function getHomeownersCarrier(carrierKey) {
  return HOMEOWNERS_CARRIER_REGISTRY[carrierKey] || null;
}
