export const RETIREMENT_TYPE_REGISTRY = {
  "401k": {
    retirement_type_key: "401k",
    display_name: "401(k)",
    major_category: "employer_plan",
    sub_category: "defined_contribution",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: true,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["401(k)", "participant statement"],
    common_fields_expected: ["current_balance", "vested_balance", "employee_contributions", "employer_match"],
  },
  roth_401k: {
    retirement_type_key: "roth_401k",
    display_name: "Roth 401(k)",
    major_category: "employer_plan",
    sub_category: "defined_contribution",
    tax_treatment: "roth",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: true,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["Roth 401(k)", "designated Roth account"],
    common_fields_expected: ["current_balance", "roth_balance", "employee_contributions"],
  },
  simple_401k: {
    retirement_type_key: "simple_401k",
    display_name: "SIMPLE 401(k)",
    major_category: "employer_plan",
    sub_category: "defined_contribution",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["simple 401(k)"],
    common_fields_expected: ["current_balance", "employee_contributions", "employer_contributions"],
  },
  safe_harbor_401k: {
    retirement_type_key: "safe_harbor_401k",
    display_name: "Safe Harbor 401(k)",
    major_category: "employer_plan",
    sub_category: "defined_contribution",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: true,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["safe harbor 401(k)"],
    common_fields_expected: ["current_balance", "employee_contributions", "employer_match"],
  },
  "403b": {
    retirement_type_key: "403b",
    display_name: "403(b)",
    major_category: "employer_plan",
    sub_category: "tax_sheltered_annuity",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: true,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["403(b)", "tax sheltered annuity"],
    common_fields_expected: ["current_balance", "vested_balance", "employee_contributions", "loan_balance"],
  },
  roth_403b: {
    retirement_type_key: "roth_403b",
    display_name: "Roth 403(b)",
    major_category: "employer_plan",
    sub_category: "tax_sheltered_annuity",
    tax_treatment: "roth",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: true,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["Roth 403(b)"],
    common_fields_expected: ["current_balance", "roth_balance", "employee_contributions"],
  },
  "457b_governmental": {
    retirement_type_key: "457b_governmental",
    display_name: "457(b) Governmental",
    major_category: "employer_plan",
    sub_category: "deferred_compensation",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["457(b)", "governmental deferred compensation"],
    common_fields_expected: ["current_balance", "employee_contributions", "allocation_summary"],
  },
  "457b_nongovernmental": {
    retirement_type_key: "457b_nongovernmental",
    display_name: "457(b) Non-Governmental",
    major_category: "employer_plan",
    sub_category: "deferred_compensation",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: false,
    rmd_relevant: true,
    common_document_labels: ["non-governmental 457(b)"],
    common_fields_expected: ["current_balance", "employee_contributions", "distribution_status"],
  },
  tsp: {
    retirement_type_key: "tsp",
    display_name: "Thrift Savings Plan",
    major_category: "employer_plan",
    sub_category: "federal_retirement_plan",
    tax_treatment: "mixed",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: true,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["thrift savings plan", "tsp participant statement"],
    common_fields_expected: ["current_balance", "loan_balance", "allocation_summary", "beneficiary_present"],
  },
  profit_sharing_plan: {
    retirement_type_key: "profit_sharing_plan",
    display_name: "Profit Sharing Plan",
    major_category: "employer_plan",
    sub_category: "defined_contribution",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: true,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["profit sharing plan"],
    common_fields_expected: ["current_balance", "employer_contributions", "vested_balance"],
  },
  esop: {
    retirement_type_key: "esop",
    display_name: "Employee Stock Ownership Plan",
    major_category: "employer_plan",
    sub_category: "company_stock_plan",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["employee stock ownership plan", "esop"],
    common_fields_expected: ["current_balance", "vested_balance", "employer_contributions"],
  },
  money_purchase_plan: {
    retirement_type_key: "money_purchase_plan",
    display_name: "Money Purchase Plan",
    major_category: "employer_plan",
    sub_category: "defined_contribution",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["money purchase plan"],
    common_fields_expected: ["current_balance", "employer_contributions", "vested_balance"],
  },
  sarsep: {
    retirement_type_key: "sarsep",
    display_name: "SARSEP",
    major_category: "employer_plan",
    sub_category: "legacy_salary_reduction_plan",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["sarsep"],
    common_fields_expected: ["current_balance", "employee_contributions", "employer_contributions"],
  },
  traditional_ira: {
    retirement_type_key: "traditional_ira",
    display_name: "Traditional IRA",
    major_category: "ira",
    sub_category: "individual_retirement_account",
    tax_treatment: "pre_tax",
    employer_sponsored: false,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["traditional ira", "ira statement"],
    common_fields_expected: ["current_balance", "rollover_balance", "ytd_contributions", "beneficiary_present"],
  },
  roth_ira: {
    retirement_type_key: "roth_ira",
    display_name: "Roth IRA",
    major_category: "ira",
    sub_category: "individual_retirement_account",
    tax_treatment: "roth",
    employer_sponsored: false,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: false,
    common_document_labels: ["roth ira"],
    common_fields_expected: ["current_balance", "roth_balance", "ytd_contributions"],
  },
  rollover_ira: {
    retirement_type_key: "rollover_ira",
    display_name: "Rollover IRA",
    major_category: "ira",
    sub_category: "rollover_account",
    tax_treatment: "pre_tax",
    employer_sponsored: false,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["rollover ira"],
    common_fields_expected: ["current_balance", "rollover_balance", "beneficiary_present"],
  },
  inherited_ira: {
    retirement_type_key: "inherited_ira",
    display_name: "Inherited IRA",
    major_category: "ira",
    sub_category: "beneficiary_account",
    tax_treatment: "mixed",
    employer_sponsored: false,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: false,
    rmd_relevant: true,
    common_document_labels: ["inherited ira", "beneficiary ira"],
    common_fields_expected: ["current_balance", "rmd_due", "rmd_taken", "beneficiary_status_known"],
  },
  sep_ira: {
    retirement_type_key: "sep_ira",
    display_name: "SEP IRA",
    major_category: "ira",
    sub_category: "small_business_ira",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["sep ira"],
    common_fields_expected: ["current_balance", "employer_contributions", "beneficiary_present"],
  },
  simple_ira: {
    retirement_type_key: "simple_ira",
    display_name: "SIMPLE IRA",
    major_category: "ira",
    sub_category: "small_business_ira",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["simple ira"],
    common_fields_expected: ["current_balance", "employee_contributions", "employer_contributions"],
  },
  payroll_deduction_ira: {
    retirement_type_key: "payroll_deduction_ira",
    display_name: "Payroll Deduction IRA",
    major_category: "ira",
    sub_category: "individual_retirement_account",
    tax_treatment: "mixed",
    employer_sponsored: true,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["payroll deduction ira"],
    common_fields_expected: ["current_balance", "employee_contributions", "beneficiary_present"],
  },
  defined_benefit_pension: {
    retirement_type_key: "defined_benefit_pension",
    display_name: "Defined Benefit Pension",
    major_category: "pension",
    sub_category: "defined_benefit",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: false,
    benefit_based: true,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: false,
    rmd_relevant: true,
    common_document_labels: ["defined benefit", "pension estimate"],
    common_fields_expected: ["monthly_benefit_estimate", "accrued_benefit_estimate", "service_years"],
  },
  cash_balance_plan: {
    retirement_type_key: "cash_balance_plan",
    display_name: "Cash Balance Plan",
    major_category: "pension",
    sub_category: "hybrid_defined_benefit",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: true,
    benefit_based: true,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["cash balance plan"],
    common_fields_expected: ["cash_balance", "accrued_benefit_estimate", "lump_sum_estimate"],
  },
  government_pension: {
    retirement_type_key: "government_pension",
    display_name: "Government Pension",
    major_category: "pension",
    sub_category: "public_defined_benefit",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: false,
    benefit_based: true,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: false,
    rmd_relevant: true,
    common_document_labels: ["government pension", "retirement system estimate"],
    common_fields_expected: ["monthly_benefit_estimate", "normal_retirement_age", "service_years"],
  },
  frozen_pension: {
    retirement_type_key: "frozen_pension",
    display_name: "Frozen Pension",
    major_category: "pension",
    sub_category: "legacy_defined_benefit",
    tax_treatment: "pre_tax",
    employer_sponsored: true,
    account_based: false,
    benefit_based: true,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: false,
    rmd_relevant: true,
    common_document_labels: ["frozen pension"],
    common_fields_expected: ["monthly_benefit_estimate", "benefit_commencement_status", "service_years"],
  },
  annuity_payout_benefit: {
    retirement_type_key: "annuity_payout_benefit",
    display_name: "Annuity Payout Benefit",
    major_category: "pension",
    sub_category: "income_stream",
    tax_treatment: "mixed",
    employer_sponsored: false,
    account_based: false,
    benefit_based: true,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: false,
    rmd_relevant: true,
    common_document_labels: ["annuity payout", "benefit payment"],
    common_fields_expected: ["monthly_benefit_estimate", "distribution_status", "survivor_option"],
  },
  qdro_related_retirement_split: {
    retirement_type_key: "qdro_related_retirement_split",
    display_name: "QDRO-Related Retirement Split",
    major_category: "special_case",
    sub_category: "court_ordered_split",
    tax_treatment: "mixed",
    employer_sponsored: false,
    account_based: true,
    benefit_based: true,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["qdro", "domestic relations order"],
    common_fields_expected: ["current_balance", "distribution_status", "beneficiary_status_known"],
  },
  rmd_relevant_retirement_account: {
    retirement_type_key: "rmd_relevant_retirement_account",
    display_name: "RMD-Relevant Retirement Account",
    major_category: "special_case",
    sub_category: "distribution_monitoring",
    tax_treatment: "mixed",
    employer_sponsored: false,
    account_based: true,
    benefit_based: false,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["required minimum distribution", "rmd notice"],
    common_fields_expected: ["current_balance", "rmd_due", "rmd_taken"],
  },
  terminated_employer_plan: {
    retirement_type_key: "terminated_employer_plan",
    display_name: "Terminated Employer Plan",
    major_category: "special_case",
    sub_category: "legacy_employer_plan",
    tax_treatment: "mixed",
    employer_sponsored: true,
    account_based: true,
    benefit_based: true,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: true,
    rmd_relevant: true,
    common_document_labels: ["terminated plan", "former employer plan"],
    common_fields_expected: ["current_balance", "distribution_status", "rollover_balance"],
  },
  payout_only_legacy_retirement_plan: {
    retirement_type_key: "payout_only_legacy_retirement_plan",
    display_name: "Payout-Only Legacy Retirement Plan",
    major_category: "special_case",
    sub_category: "income_distribution",
    tax_treatment: "mixed",
    employer_sponsored: false,
    account_based: false,
    benefit_based: true,
    loan_possible: false,
    beneficiary_relevant: true,
    rollover_relevant: false,
    rmd_relevant: true,
    common_document_labels: ["retirement payout", "benefit payment"],
    common_fields_expected: ["monthly_benefit_estimate", "distribution_status", "beneficiary_status_known"],
  },
};

export const RETIREMENT_TYPE_KEYS = Object.freeze(Object.keys(RETIREMENT_TYPE_REGISTRY));

export function listRetirementTypes() {
  return Object.values(RETIREMENT_TYPE_REGISTRY);
}

export function getRetirementType(retirementTypeKey) {
  return RETIREMENT_TYPE_REGISTRY[retirementTypeKey] || null;
}
