export const RETIREMENT_PROVIDER_REGISTRY = {
  fidelity: {
    institution_key: "fidelity",
    display_name: "Fidelity",
    institution_type: "retirement_provider",
    retirement_supported_types: ["401k", "roth_401k", "403b", "traditional_ira", "roth_ira", "rollover_ira"],
    known_portal_urls: ["https://netbenefits.fidelity.com", "https://www.fidelity.com"],
    known_statement_patterns: ["netbenefits", "fidelity workplace", "retirement savings statement"],
    known_document_labels: ["participant statement", "retirement analysis", "beneficiary designation"],
    known_beneficiary_section_labels: ["beneficiary information", "designated beneficiaries"],
    known_loan_section_labels: ["loan summary", "outstanding loan", "loan balance"],
    known_allocation_section_labels: ["asset allocation", "investment options", "fund performance"],
    notes: "Strong employer plan and IRA coverage.",
  },
  vanguard: {
    institution_key: "vanguard",
    display_name: "Vanguard",
    institution_type: "retirement_provider",
    retirement_supported_types: ["401k", "403b", "traditional_ira", "roth_ira", "rollover_ira", "sep_ira"],
    known_portal_urls: ["https://ownyourfuture.vanguard.com", "https://www.vanguard.com"],
    known_statement_patterns: ["vanguard retirement", "participant statement"],
    known_document_labels: ["quarterly statement", "plan summary", "beneficiary designation"],
    known_beneficiary_section_labels: ["beneficiary designation"],
    known_loan_section_labels: ["loan activity", "loan details"],
    known_allocation_section_labels: ["portfolio allocation", "investment holdings"],
    notes: "Common across 401(k), 403(b), and IRA households.",
  },
  charles_schwab: {
    institution_key: "charles_schwab",
    display_name: "Charles Schwab",
    institution_type: "retirement_provider",
    retirement_supported_types: ["401k", "traditional_ira", "roth_ira", "rollover_ira", "inherited_ira"],
    known_portal_urls: ["https://workplace.schwab.com", "https://www.schwab.com"],
    known_statement_patterns: ["schwab retirement plan services", "account statement"],
    known_document_labels: ["participant statement", "account summary"],
    known_beneficiary_section_labels: ["beneficiary designation", "transfer on death"],
    known_loan_section_labels: ["loan details", "loan summary"],
    known_allocation_section_labels: ["holdings detail", "asset allocation"],
    notes: "Supports both workplace and retail retirement accounts.",
  },
  empower: {
    institution_key: "empower",
    display_name: "Empower",
    institution_type: "retirement_provider",
    retirement_supported_types: ["401k", "403b", "457b_governmental", "profit_sharing_plan", "esop"],
    known_portal_urls: ["https://participant.empower-retirement.com"],
    known_statement_patterns: ["empower retirement", "plan balance", "participant account statement"],
    known_document_labels: ["participant statement", "fee disclosure", "loan statement"],
    known_beneficiary_section_labels: ["beneficiary information"],
    known_loan_section_labels: ["loan summary", "loan repayment"],
    known_allocation_section_labels: ["investment election", "asset allocation"],
    notes: "Large provider for employer-sponsored retirement plans.",
  },
  principal: {
    institution_key: "principal",
    display_name: "Principal",
    institution_type: "retirement_provider",
    retirement_supported_types: ["401k", "403b", "profit_sharing_plan", "defined_benefit_pension"],
    known_portal_urls: ["https://www.principal.com"],
    known_statement_patterns: ["principal retirement account statement"],
    known_document_labels: ["participant statement", "plan summary", "beneficiary form"],
    known_beneficiary_section_labels: ["beneficiary", "designation"],
    known_loan_section_labels: ["plan loan", "outstanding balance"],
    known_allocation_section_labels: ["investment lineup", "allocation summary"],
    notes: "Often used for small and midsize employer plans.",
  },
  t_rowe_price: {
    institution_key: "t_rowe_price",
    display_name: "T. Rowe Price",
    institution_type: "retirement_provider",
    retirement_supported_types: ["401k", "403b", "traditional_ira", "roth_ira", "rollover_ira"],
    known_portal_urls: ["https://www.troweprice.com"],
    known_statement_patterns: ["t. rowe price retirement"],
    known_document_labels: ["participant statement", "retirement statement"],
    known_beneficiary_section_labels: ["beneficiary designation"],
    known_loan_section_labels: ["loan balance", "loan details"],
    known_allocation_section_labels: ["fund allocation", "investment mix"],
    notes: "Target-date and participant statements commonly seen.",
  },
  voya: {
    institution_key: "voya",
    display_name: "Voya",
    institution_type: "retirement_provider",
    retirement_supported_types: ["401k", "403b", "457b_governmental", "457b_nongovernmental"],
    known_portal_urls: ["https://my.voya.com"],
    known_statement_patterns: ["voya retirement insurance and annuity", "plan overview"],
    known_document_labels: ["participant statement", "plan administrator notice"],
    known_beneficiary_section_labels: ["beneficiary information"],
    known_loan_section_labels: ["loan summary"],
    known_allocation_section_labels: ["investment elections", "performance by fund"],
    notes: "Common in public and nonprofit plans.",
  },
  tiaa: {
    institution_key: "tiaa",
    display_name: "TIAA",
    institution_type: "retirement_provider",
    retirement_supported_types: ["403b", "defined_benefit_pension", "traditional_ira", "roth_ira"],
    known_portal_urls: ["https://www.tiaa.org"],
    known_statement_patterns: ["tiaa account statement", "retirement annuity"],
    known_document_labels: ["participant statement", "annuity contract summary"],
    known_beneficiary_section_labels: ["beneficiary designation"],
    known_loan_section_labels: ["loan summary"],
    known_allocation_section_labels: ["allocation by investment", "account balances"],
    notes: "Frequent in higher-education retirement ecosystems.",
  },
  lincoln: {
    institution_key: "lincoln",
    display_name: "Lincoln Financial",
    institution_type: "retirement_provider",
    retirement_supported_types: ["401k", "403b", "457b_governmental"],
    known_portal_urls: ["https://retirement.lfg.com"],
    known_statement_patterns: ["lincoln financial retirement"],
    known_document_labels: ["participant statement", "fee disclosure"],
    known_beneficiary_section_labels: ["beneficiary"],
    known_loan_section_labels: ["loan balance", "loan summary"],
    known_allocation_section_labels: ["investment options", "allocation mix"],
    notes: "Retirement business separate from life policy intelligence.",
  },
  nationwide: {
    institution_key: "nationwide",
    display_name: "Nationwide Retirement Solutions",
    institution_type: "retirement_provider",
    retirement_supported_types: ["401k", "403b", "457b_governmental", "457b_nongovernmental"],
    known_portal_urls: ["https://www.nrsforu.com"],
    known_statement_patterns: ["nationwide retirement solutions", "participant account statement"],
    known_document_labels: ["participant statement", "annual statement"],
    known_beneficiary_section_labels: ["beneficiary information"],
    known_loan_section_labels: ["loan activity", "loan balance"],
    known_allocation_section_labels: ["asset allocation", "investment election"],
    notes: "Useful bridge between retirement and insurance households.",
  },
  transamerica_retirement: {
    institution_key: "transamerica_retirement",
    display_name: "Transamerica Retirement",
    institution_type: "retirement_provider",
    retirement_supported_types: ["401k", "403b", "457b_governmental", "simple_ira"],
    known_portal_urls: ["https://www.transamerica.com"],
    known_statement_patterns: ["transamerica retirement solutions"],
    known_document_labels: ["participant statement", "beneficiary designation", "loan statement"],
    known_beneficiary_section_labels: ["beneficiary"],
    known_loan_section_labels: ["loan statement", "loan payment"],
    known_allocation_section_labels: ["investment election", "fund allocation"],
    notes: "Starter provider support for legacy retirement books.",
  },
  adp: {
    institution_key: "adp",
    display_name: "ADP Retirement Services",
    institution_type: "retirement_provider",
    retirement_supported_types: ["401k", "safe_harbor_401k", "simple_401k"],
    known_portal_urls: ["https://mykplan.adp.com"],
    known_statement_patterns: ["adp retirement", "participant statement"],
    known_document_labels: ["participant statement", "plan summary"],
    known_beneficiary_section_labels: ["beneficiary"],
    known_loan_section_labels: ["loan summary"],
    known_allocation_section_labels: ["asset allocation"],
    notes: "Common in payroll-integrated small business plans.",
  },
  paychex: {
    institution_key: "paychex",
    display_name: "Paychex Retirement Services",
    institution_type: "retirement_provider",
    retirement_supported_types: ["401k", "safe_harbor_401k", "simple_ira"],
    known_portal_urls: ["https://www.paychexflex.com"],
    known_statement_patterns: ["paychex retirement services"],
    known_document_labels: ["participant statement", "administrator notice"],
    known_beneficiary_section_labels: ["beneficiary"],
    known_loan_section_labels: ["loan summary"],
    known_allocation_section_labels: ["investment allocation"],
    notes: "Starter payroll-linked retirement registry entry.",
  },
  newport: {
    institution_key: "newport",
    display_name: "Newport",
    institution_type: "retirement_provider",
    retirement_supported_types: ["401k", "profit_sharing_plan", "cash_balance_plan"],
    known_portal_urls: ["https://participant.newportgroup.com"],
    known_statement_patterns: ["newport retirement services"],
    known_document_labels: ["participant statement", "plan summary"],
    known_beneficiary_section_labels: ["beneficiary"],
    known_loan_section_labels: ["loan balance"],
    known_allocation_section_labels: ["allocation summary"],
    notes: "Useful for privately administered employer plans.",
  },
  tsp: {
    institution_key: "tsp",
    display_name: "Thrift Savings Plan",
    institution_type: "government_retirement_provider",
    retirement_supported_types: ["tsp"],
    known_portal_urls: ["https://www.tsp.gov"],
    known_statement_patterns: ["thrift savings plan", "tsp statement"],
    known_document_labels: ["participant statement", "loan summary", "beneficiary information"],
    known_beneficiary_section_labels: ["beneficiaries", "designation of beneficiary"],
    known_loan_section_labels: ["loan details", "loan balance"],
    known_allocation_section_labels: ["fund allocation", "contribution allocation"],
    notes: "Federal plan with distinct portal, loans, and beneficiary rules.",
  },
  public_pension_system_generic: {
    institution_key: "public_pension_system_generic",
    display_name: "Public Pension System",
    institution_type: "pension_system",
    retirement_supported_types: ["government_pension", "defined_benefit_pension", "cash_balance_plan"],
    known_portal_urls: [],
    known_statement_patterns: ["retirement system", "benefit estimate", "member annual statement"],
    known_document_labels: ["pension estimate", "annual benefit statement", "member statement"],
    known_beneficiary_section_labels: ["survivor beneficiary", "beneficiary information"],
    known_loan_section_labels: [],
    known_allocation_section_labels: [],
    notes: "Generic public pension starter profile until system-specific registries are added.",
  },
};

export const RETIREMENT_PROVIDER_KEYS = Object.freeze(Object.keys(RETIREMENT_PROVIDER_REGISTRY));

export function listRetirementProviders() {
  return Object.values(RETIREMENT_PROVIDER_REGISTRY);
}

export function getRetirementProvider(institutionKey) {
  return RETIREMENT_PROVIDER_REGISTRY[institutionKey] || null;
}
