export const WARRANTY_TYPE_REGISTRY = {
  home_warranty_contract: {
    warranty_type_key: "home_warranty_contract",
    display_name: "Home Warranty Contract",
    major_category: "home_service",
    serial_relevant: false,
    product_model_relevant: false,
    renewal_possible: true,
    proof_of_purchase_relevant: true,
    claim_contact_relevant: true,
    home_related_reference: true,
    vehicle_related_reference: false,
    electronics_related_reference: false,
    common_document_labels: ["home warranty", "service contract", "coverage summary"],
    common_fields_expected: ["covered_item_name", "effective_date", "expiration_date", "deductible_or_service_fee"],
  },
  appliance_warranty: {
    warranty_type_key: "appliance_warranty",
    display_name: "Appliance Warranty",
    major_category: "appliance",
    serial_relevant: true,
    product_model_relevant: true,
    renewal_possible: true,
    proof_of_purchase_relevant: true,
    claim_contact_relevant: true,
    home_related_reference: true,
    vehicle_related_reference: false,
    electronics_related_reference: false,
    common_document_labels: ["appliance warranty", "manufacturer warranty"],
    common_fields_expected: ["model_number", "serial_number_masked", "purchase_date", "expiration_date"],
  },
  electronics_protection_plan: {
    warranty_type_key: "electronics_protection_plan",
    display_name: "Electronics Protection Plan",
    major_category: "electronics",
    serial_relevant: true,
    product_model_relevant: true,
    renewal_possible: true,
    proof_of_purchase_relevant: true,
    claim_contact_relevant: true,
    home_related_reference: false,
    vehicle_related_reference: false,
    electronics_related_reference: true,
    common_document_labels: ["protection plan", "electronics coverage", "device protection"],
    common_fields_expected: ["covered_item_name", "model_number", "serial_number_masked", "effective_date"],
  },
  vehicle_service_contract_reference: {
    warranty_type_key: "vehicle_service_contract_reference",
    display_name: "Vehicle Service Contract Reference",
    major_category: "vehicle_service",
    serial_relevant: true,
    product_model_relevant: true,
    renewal_possible: true,
    proof_of_purchase_relevant: true,
    claim_contact_relevant: true,
    home_related_reference: false,
    vehicle_related_reference: true,
    electronics_related_reference: false,
    common_document_labels: ["service contract", "extended auto warranty", "vehicle protection plan"],
    common_fields_expected: ["covered_item_name", "contract_number", "expiration_date", "property_or_vehicle_reference"],
  },
  hvac_service_contract: {
    warranty_type_key: "hvac_service_contract",
    display_name: "HVAC Service Contract",
    major_category: "home_service",
    serial_relevant: true,
    product_model_relevant: true,
    renewal_possible: true,
    proof_of_purchase_relevant: true,
    claim_contact_relevant: true,
    home_related_reference: true,
    vehicle_related_reference: false,
    electronics_related_reference: false,
    common_document_labels: ["hvac service agreement", "maintenance contract"],
    common_fields_expected: ["covered_item_name", "model_number", "installation_date", "coverage_end_date"],
  },
  roof_warranty_reference: {
    warranty_type_key: "roof_warranty_reference",
    display_name: "Roof Warranty Reference",
    major_category: "structural_home",
    serial_relevant: false,
    product_model_relevant: false,
    renewal_possible: false,
    proof_of_purchase_relevant: true,
    claim_contact_relevant: true,
    home_related_reference: true,
    vehicle_related_reference: false,
    electronics_related_reference: false,
    common_document_labels: ["roof warranty", "workmanship warranty"],
    common_fields_expected: ["covered_item_name", "installation_date", "coverage_end_date", "claim_contact"],
  },
  solar_warranty_reference: {
    warranty_type_key: "solar_warranty_reference",
    display_name: "Solar Warranty Reference",
    major_category: "home_energy",
    serial_relevant: true,
    product_model_relevant: true,
    renewal_possible: false,
    proof_of_purchase_relevant: true,
    claim_contact_relevant: true,
    home_related_reference: true,
    vehicle_related_reference: false,
    electronics_related_reference: true,
    common_document_labels: ["solar warranty", "panel warranty", "inverter warranty"],
    common_fields_expected: ["covered_item_name", "model_number", "serial_number_masked", "coverage_end_date"],
  },
  builders_warranty_reference: {
    warranty_type_key: "builders_warranty_reference",
    display_name: "Builders Warranty Reference",
    major_category: "structural_home",
    serial_relevant: false,
    product_model_relevant: false,
    renewal_possible: false,
    proof_of_purchase_relevant: true,
    claim_contact_relevant: true,
    home_related_reference: true,
    vehicle_related_reference: false,
    electronics_related_reference: false,
    common_document_labels: ["builders warranty", "new construction warranty"],
    common_fields_expected: ["property_or_vehicle_reference", "effective_date", "expiration_date", "claim_contact"],
  },
  furniture_protection_plan_reference: {
    warranty_type_key: "furniture_protection_plan_reference",
    display_name: "Furniture Protection Plan Reference",
    major_category: "furniture",
    serial_relevant: false,
    product_model_relevant: true,
    renewal_possible: true,
    proof_of_purchase_relevant: true,
    claim_contact_relevant: true,
    home_related_reference: true,
    vehicle_related_reference: false,
    electronics_related_reference: false,
    common_document_labels: ["furniture protection plan", "furniture warranty"],
    common_fields_expected: ["covered_item_name", "purchase_date", "expiration_date", "proof_of_purchase_reference"],
  },
  extended_service_plan_generic: {
    warranty_type_key: "extended_service_plan_generic",
    display_name: "Extended Service Plan",
    major_category: "service_contract",
    serial_relevant: true,
    product_model_relevant: true,
    renewal_possible: true,
    proof_of_purchase_relevant: true,
    claim_contact_relevant: true,
    home_related_reference: true,
    vehicle_related_reference: true,
    electronics_related_reference: true,
    common_document_labels: ["extended service plan", "service agreement"],
    common_fields_expected: ["contract_number", "covered_item_name", "effective_date", "expiration_date"],
  },
  warranty_generic: {
    warranty_type_key: "warranty_generic",
    display_name: "Warranty / Service Contract",
    major_category: "generic_warranty",
    serial_relevant: true,
    product_model_relevant: true,
    renewal_possible: true,
    proof_of_purchase_relevant: true,
    claim_contact_relevant: true,
    home_related_reference: true,
    vehicle_related_reference: true,
    electronics_related_reference: true,
    common_document_labels: ["warranty", "service contract", "protection plan"],
    common_fields_expected: ["provider_name", "contract_number", "covered_item_name", "contract_status"],
  },
};

export const WARRANTY_TYPE_KEYS = Object.freeze(Object.keys(WARRANTY_TYPE_REGISTRY));

export function listWarrantyTypes() {
  return Object.values(WARRANTY_TYPE_REGISTRY);
}

export function getWarrantyType(warrantyTypeKey) {
  return WARRANTY_TYPE_REGISTRY[warrantyTypeKey] || null;
}
