export const MORTGAGE_LOAN_TYPE_REGISTRY = {
  conventional_fixed_mortgage: {
    mortgage_loan_type_key: "conventional_fixed_mortgage",
    display_name: "Conventional Fixed Mortgage",
    major_category: "primary_mortgage",
    occupancy_relevant: true,
    escrow_relevant: true,
    adjustable_rate_possible: false,
    payoff_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["mortgage statement", "fixed rate note", "monthly statement"],
    common_fields_expected: ["current_principal_balance", "monthly_payment", "interest_rate", "escrow_payment"],
  },
  adjustable_rate_mortgage: {
    mortgage_loan_type_key: "adjustable_rate_mortgage",
    display_name: "Adjustable Rate Mortgage",
    major_category: "primary_mortgage",
    occupancy_relevant: true,
    escrow_relevant: true,
    adjustable_rate_possible: true,
    payoff_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["arm statement", "adjustable rate mortgage", "rate adjustment notice"],
    common_fields_expected: ["current_principal_balance", "interest_rate", "arm_adjustment_note", "next_due_date"],
  },
  fha_mortgage: {
    mortgage_loan_type_key: "fha_mortgage",
    display_name: "FHA Mortgage",
    major_category: "government_backed",
    occupancy_relevant: true,
    escrow_relevant: true,
    adjustable_rate_possible: true,
    payoff_relevant: true,
    investment_property_relevant: false,
    common_document_labels: ["fha", "mortgage insurance premium", "monthly statement"],
    common_fields_expected: ["current_principal_balance", "monthly_payment", "pmi_mip_amount", "escrow_payment"],
  },
  va_mortgage: {
    mortgage_loan_type_key: "va_mortgage",
    display_name: "VA Mortgage",
    major_category: "government_backed",
    occupancy_relevant: true,
    escrow_relevant: true,
    adjustable_rate_possible: true,
    payoff_relevant: true,
    investment_property_relevant: false,
    common_document_labels: ["va loan", "mortgage statement"],
    common_fields_expected: ["current_principal_balance", "monthly_payment", "interest_rate", "escrow_payment"],
  },
  jumbo_mortgage: {
    mortgage_loan_type_key: "jumbo_mortgage",
    display_name: "Jumbo Mortgage",
    major_category: "primary_mortgage",
    occupancy_relevant: true,
    escrow_relevant: true,
    adjustable_rate_possible: true,
    payoff_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["jumbo", "monthly statement", "payoff statement"],
    common_fields_expected: ["current_principal_balance", "monthly_payment", "interest_rate", "payoff_amount"],
  },
  heloc: {
    mortgage_loan_type_key: "heloc",
    display_name: "HELOC",
    major_category: "equity_line",
    occupancy_relevant: true,
    escrow_relevant: false,
    adjustable_rate_possible: true,
    payoff_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["heloc", "home equity line", "draw statement"],
    common_fields_expected: ["current_principal_balance", "interest_rate", "monthly_payment", "loan_status"],
  },
  second_mortgage: {
    mortgage_loan_type_key: "second_mortgage",
    display_name: "Second Mortgage",
    major_category: "junior_lien",
    occupancy_relevant: true,
    escrow_relevant: false,
    adjustable_rate_possible: true,
    payoff_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["second mortgage", "junior lien"],
    common_fields_expected: ["current_principal_balance", "monthly_payment", "interest_rate", "payoff_amount"],
  },
  refinance_mortgage: {
    mortgage_loan_type_key: "refinance_mortgage",
    display_name: "Refinance Mortgage",
    major_category: "refinance",
    occupancy_relevant: true,
    escrow_relevant: true,
    adjustable_rate_possible: true,
    payoff_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["refinance", "closing disclosure", "mortgage statement"],
    common_fields_expected: ["origination_date", "current_principal_balance", "interest_rate", "monthly_payment"],
  },
  investment_property_mortgage: {
    mortgage_loan_type_key: "investment_property_mortgage",
    display_name: "Investment Property Mortgage",
    major_category: "investment_property",
    occupancy_relevant: true,
    escrow_relevant: true,
    adjustable_rate_possible: true,
    payoff_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["investment property", "rental property mortgage"],
    common_fields_expected: ["property_address", "current_principal_balance", "monthly_payment", "occupancy_type"],
  },
  private_money_mortgage: {
    mortgage_loan_type_key: "private_money_mortgage",
    display_name: "Private Money Mortgage",
    major_category: "private_lending",
    occupancy_relevant: true,
    escrow_relevant: false,
    adjustable_rate_possible: true,
    payoff_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["private lender", "note", "payoff demand"],
    common_fields_expected: ["borrower_name", "current_principal_balance", "interest_rate", "loan_status"],
  },
  seller_carry_note: {
    mortgage_loan_type_key: "seller_carry_note",
    display_name: "Seller Carry Note",
    major_category: "private_lending",
    occupancy_relevant: true,
    escrow_relevant: false,
    adjustable_rate_possible: true,
    payoff_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["seller carry", "promissory note", "owner financing"],
    common_fields_expected: ["borrower_name", "loan_number_masked", "monthly_payment", "payoff_amount"],
  },
  loan_modification_reference: {
    mortgage_loan_type_key: "loan_modification_reference",
    display_name: "Loan Modification Reference",
    major_category: "distressed_or_modified",
    occupancy_relevant: true,
    escrow_relevant: true,
    adjustable_rate_possible: true,
    payoff_relevant: true,
    investment_property_relevant: true,
    common_document_labels: ["loan modification", "trial payment plan", "modification notice"],
    common_fields_expected: ["loan_status", "monthly_payment", "interest_rate", "modification_notice_present"],
  },
};

export const MORTGAGE_LOAN_TYPE_KEYS = Object.freeze(Object.keys(MORTGAGE_LOAN_TYPE_REGISTRY));

export function listMortgageLoanTypes() {
  return Object.values(MORTGAGE_LOAN_TYPE_REGISTRY);
}

export function getMortgageLoanType(loanTypeKey) {
  return MORTGAGE_LOAN_TYPE_REGISTRY[loanTypeKey] || null;
}
