export const MORTGAGE_LENDER_REGISTRY = {
  rocket_mortgage: {
    lender_key: "rocket_mortgage",
    display_name: "Rocket Mortgage",
    institution_type: "mortgage_servicer",
    known_portal_urls: ["https://www.rocketmortgage.com"],
    known_statement_patterns: ["rocket mortgage", "monthly mortgage statement"],
    known_balance_labels: ["principal balance", "unpaid principal balance", "loan balance"],
    known_payment_labels: ["monthly payment", "principal", "interest"],
    known_escrow_labels: ["escrow", "taxes", "insurance"],
    notes: "Starter servicer profile for standard mortgage statements.",
  },
  wells_fargo_home_mortgage: {
    lender_key: "wells_fargo_home_mortgage",
    display_name: "Wells Fargo Home Mortgage",
    institution_type: "mortgage_servicer",
    known_portal_urls: ["https://www.wellsfargo.com"],
    known_statement_patterns: ["wells fargo home mortgage", "mortgage statement"],
    known_balance_labels: ["principal balance", "escrow balance"],
    known_payment_labels: ["payment due", "principal", "interest"],
    known_escrow_labels: ["escrow", "hazard insurance", "property taxes"],
    notes: "Common large-bank mortgage servicer.",
  },
  chase_home_lending: {
    lender_key: "chase_home_lending",
    display_name: "Chase Home Lending",
    institution_type: "mortgage_servicer",
    known_portal_urls: ["https://www.chase.com"],
    known_statement_patterns: ["chase home lending", "monthly statement"],
    known_balance_labels: ["unpaid principal balance", "payoff amount"],
    known_payment_labels: ["monthly payment amount", "principal", "interest"],
    known_escrow_labels: ["escrow", "tax", "insurance"],
    notes: "Starter profile for Chase-serviced loans.",
  },
  mr_cooper: {
    lender_key: "mr_cooper",
    display_name: "Mr. Cooper",
    institution_type: "mortgage_servicer",
    known_portal_urls: ["https://www.mrcooper.com"],
    known_statement_patterns: ["mr cooper", "loan statement"],
    known_balance_labels: ["principal balance", "current balance"],
    known_payment_labels: ["payment due", "amount due"],
    known_escrow_labels: ["escrow", "taxes and insurance"],
    notes: "Common modern servicer profile.",
  },
  freedom_mortgage: {
    lender_key: "freedom_mortgage",
    display_name: "Freedom Mortgage",
    institution_type: "mortgage_servicer",
    known_portal_urls: ["https://www.freedommortgage.com"],
    known_statement_patterns: ["freedom mortgage", "monthly statement"],
    known_balance_labels: ["current principal balance", "loan balance"],
    known_payment_labels: ["payment due", "principal", "interest"],
    known_escrow_labels: ["escrow", "taxes", "insurance"],
    notes: "Starter support for standard servicing statements.",
  },
  pennymac: {
    lender_key: "pennymac",
    display_name: "Pennymac",
    institution_type: "mortgage_servicer",
    known_portal_urls: ["https://www.pennymac.com"],
    known_statement_patterns: ["pennymac", "mortgage statement"],
    known_balance_labels: ["principal balance", "payoff statement"],
    known_payment_labels: ["payment due", "principal", "interest"],
    known_escrow_labels: ["escrow", "escrow balance"],
    notes: "Starter servicing profile.",
  },
  loan_depot: {
    lender_key: "loan_depot",
    display_name: "loanDepot",
    institution_type: "mortgage_servicer",
    known_portal_urls: ["https://www.loandepot.com"],
    known_statement_patterns: ["loandepot", "mortgage account statement"],
    known_balance_labels: ["principal balance", "loan balance"],
    known_payment_labels: ["monthly payment", "payment amount"],
    known_escrow_labels: ["escrow", "taxes", "insurance"],
    notes: "Starter profile for retail mortgage originator/servicer.",
  },
  us_bank_mortgage: {
    lender_key: "us_bank_mortgage",
    display_name: "U.S. Bank Mortgage",
    institution_type: "mortgage_servicer",
    known_portal_urls: ["https://www.usbank.com"],
    known_statement_patterns: ["u.s. bank mortgage", "mortgage statement"],
    known_balance_labels: ["principal balance", "payoff amount"],
    known_payment_labels: ["monthly payment", "principal", "interest"],
    known_escrow_labels: ["escrow", "escrow payment"],
    notes: "Starter large-bank mortgage profile.",
  },
  bank_of_america_home_loans: {
    lender_key: "bank_of_america_home_loans",
    display_name: "Bank of America Home Loans",
    institution_type: "mortgage_servicer",
    known_portal_urls: ["https://www.bankofamerica.com"],
    known_statement_patterns: ["bank of america home loans", "mortgage statement"],
    known_balance_labels: ["principal balance", "loan balance"],
    known_payment_labels: ["payment due", "principal", "interest"],
    known_escrow_labels: ["escrow", "taxes and insurance"],
    notes: "Starter BOA home loans profile.",
  },
  shellpoint: {
    lender_key: "shellpoint",
    display_name: "Shellpoint",
    institution_type: "mortgage_servicer",
    known_portal_urls: ["https://www.shellpointmtg.com"],
    known_statement_patterns: ["shellpoint", "monthly statement"],
    known_balance_labels: ["principal balance", "unpaid principal balance"],
    known_payment_labels: ["payment due", "late fee"],
    known_escrow_labels: ["escrow", "escrow shortage", "insurance"],
    notes: "Special servicing starter profile.",
  },
  newrez: {
    lender_key: "newrez",
    display_name: "Newrez",
    institution_type: "mortgage_servicer",
    known_portal_urls: ["https://www.newrez.com"],
    known_statement_patterns: ["newrez", "mortgage statement"],
    known_balance_labels: ["principal balance", "payoff amount"],
    known_payment_labels: ["amount due", "principal", "interest"],
    known_escrow_labels: ["escrow", "tax", "insurance"],
    notes: "Starter servicing profile.",
  },
  carrington: {
    lender_key: "carrington",
    display_name: "Carrington",
    institution_type: "mortgage_servicer",
    known_portal_urls: ["https://www.carringtonmortgage.com"],
    known_statement_patterns: ["carrington", "mortgage statement"],
    known_balance_labels: ["unpaid principal balance", "loan balance"],
    known_payment_labels: ["amount due", "late fee"],
    known_escrow_labels: ["escrow", "escrow balance"],
    notes: "Starter profile for alternative servicer visibility.",
  },
  mortgage_generic_servicer: {
    lender_key: "mortgage_generic_servicer",
    display_name: "Generic Mortgage Servicer",
    institution_type: "mortgage_servicer",
    known_portal_urls: [],
    known_statement_patterns: ["mortgage statement", "escrow statement", "payoff statement"],
    known_balance_labels: ["principal balance", "current balance", "payoff amount"],
    known_payment_labels: ["monthly payment", "principal", "interest"],
    known_escrow_labels: ["escrow", "taxes", "insurance"],
    notes: "Fallback reference for unknown mortgage lenders/servicers.",
  },
};

export const MORTGAGE_LENDER_KEYS = Object.freeze(Object.keys(MORTGAGE_LENDER_REGISTRY));

export function listMortgageLenders() {
  return Object.values(MORTGAGE_LENDER_REGISTRY);
}

export function getMortgageLender(lenderKey) {
  return MORTGAGE_LENDER_REGISTRY[lenderKey] || null;
}
