export const HEALTH_PLAN_TYPE_REGISTRY = {
  ppo_plan: {
    health_plan_type_key: "ppo_plan",
    display_name: "PPO Plan",
    major_category: "commercial",
    network_relevant: true,
    deductible_relevant: true,
    oop_relevant: true,
    prescription_relevant: true,
    family_coverage_relevant: true,
    employer_sponsored_possible: true,
    medicare_related: false,
    medicaid_related: false,
    common_document_labels: ["summary of benefits", "ppo", "group health plan"],
    common_fields_expected: ["network_name", "deductible_individual", "out_of_pocket_max_individual", "specialist_copay"],
  },
  hmo_plan: {
    health_plan_type_key: "hmo_plan",
    display_name: "HMO Plan",
    major_category: "commercial",
    network_relevant: true,
    deductible_relevant: true,
    oop_relevant: true,
    prescription_relevant: true,
    family_coverage_relevant: true,
    employer_sponsored_possible: true,
    medicare_related: false,
    medicaid_related: false,
    common_document_labels: ["hmo", "summary of benefits", "pcp required"],
    common_fields_expected: ["network_name", "pcp_required_indicator", "referral_required_indicator", "primary_care_copay"],
  },
  epo_plan: {
    health_plan_type_key: "epo_plan",
    display_name: "EPO Plan",
    major_category: "commercial",
    network_relevant: true,
    deductible_relevant: true,
    oop_relevant: true,
    prescription_relevant: true,
    family_coverage_relevant: true,
    employer_sponsored_possible: true,
    medicare_related: false,
    medicaid_related: false,
    common_document_labels: ["epo", "exclusive provider"],
    common_fields_expected: ["network_name", "in_network_only_indicator", "deductible_individual", "coinsurance_percent"],
  },
  pos_plan: {
    health_plan_type_key: "pos_plan",
    display_name: "POS Plan",
    major_category: "commercial",
    network_relevant: true,
    deductible_relevant: true,
    oop_relevant: true,
    prescription_relevant: true,
    family_coverage_relevant: true,
    employer_sponsored_possible: true,
    medicare_related: false,
    medicaid_related: false,
    common_document_labels: ["pos", "point of service"],
    common_fields_expected: ["network_name", "pcp_required_indicator", "referral_required_indicator", "deductible_individual"],
  },
  hdhp_plan: {
    health_plan_type_key: "hdhp_plan",
    display_name: "HDHP Plan",
    major_category: "commercial",
    network_relevant: true,
    deductible_relevant: true,
    oop_relevant: true,
    prescription_relevant: true,
    family_coverage_relevant: true,
    employer_sponsored_possible: true,
    medicare_related: false,
    medicaid_related: false,
    common_document_labels: ["high deductible health plan", "hdhp", "hsa compatible"],
    common_fields_expected: ["deductible_individual", "deductible_family", "out_of_pocket_max_individual", "premium_amount"],
  },
  medicare_advantage_plan: {
    health_plan_type_key: "medicare_advantage_plan",
    display_name: "Medicare Advantage Plan",
    major_category: "government_program",
    network_relevant: true,
    deductible_relevant: true,
    oop_relevant: true,
    prescription_relevant: true,
    family_coverage_relevant: false,
    employer_sponsored_possible: false,
    medicare_related: true,
    medicaid_related: false,
    common_document_labels: ["medicare advantage", "part c", "evidence of coverage"],
    common_fields_expected: ["plan_name", "policy_or_member_id_masked", "out_of_pocket_max_individual", "network_name"],
  },
  medicare_supplement_reference: {
    health_plan_type_key: "medicare_supplement_reference",
    display_name: "Medicare Supplement Reference",
    major_category: "government_program",
    network_relevant: false,
    deductible_relevant: true,
    oop_relevant: true,
    prescription_relevant: false,
    family_coverage_relevant: false,
    employer_sponsored_possible: false,
    medicare_related: true,
    medicaid_related: false,
    common_document_labels: ["medigap", "medicare supplement"],
    common_fields_expected: ["plan_name", "effective_date", "premium_amount", "plan_status"],
  },
  medicaid_plan: {
    health_plan_type_key: "medicaid_plan",
    display_name: "Medicaid Plan",
    major_category: "government_program",
    network_relevant: true,
    deductible_relevant: false,
    oop_relevant: false,
    prescription_relevant: true,
    family_coverage_relevant: true,
    employer_sponsored_possible: false,
    medicare_related: false,
    medicaid_related: true,
    common_document_labels: ["medicaid", "managed medicaid", "eligibility notice"],
    common_fields_expected: ["plan_name", "subscriber_name", "eligibility_notice_present", "network_name"],
  },
  employer_group_plan: {
    health_plan_type_key: "employer_group_plan",
    display_name: "Employer Group Plan",
    major_category: "employer_group",
    network_relevant: true,
    deductible_relevant: true,
    oop_relevant: true,
    prescription_relevant: true,
    family_coverage_relevant: true,
    employer_sponsored_possible: true,
    medicare_related: false,
    medicaid_related: false,
    common_document_labels: ["group benefits summary", "employer coverage", "open enrollment"],
    common_fields_expected: ["employer_group_name", "subscriber_name", "deductible_individual", "premium_amount"],
  },
  marketplace_individual_plan: {
    health_plan_type_key: "marketplace_individual_plan",
    display_name: "Marketplace Individual Plan",
    major_category: "individual_market",
    network_relevant: true,
    deductible_relevant: true,
    oop_relevant: true,
    prescription_relevant: true,
    family_coverage_relevant: true,
    employer_sponsored_possible: false,
    medicare_related: false,
    medicaid_related: false,
    common_document_labels: ["marketplace", "individual health plan", "exchange coverage"],
    common_fields_expected: ["plan_name", "premium_amount", "effective_date", "renewal_date"],
  },
  dental_plan_reference: {
    health_plan_type_key: "dental_plan_reference",
    display_name: "Dental Plan Reference",
    major_category: "supplemental_health",
    network_relevant: true,
    deductible_relevant: true,
    oop_relevant: false,
    prescription_relevant: false,
    family_coverage_relevant: true,
    employer_sponsored_possible: true,
    medicare_related: false,
    medicaid_related: false,
    common_document_labels: ["dental plan", "dental benefits"],
    common_fields_expected: ["plan_name", "network_name", "deductible_individual", "family_plan_indicator"],
  },
  vision_plan_reference: {
    health_plan_type_key: "vision_plan_reference",
    display_name: "Vision Plan Reference",
    major_category: "supplemental_health",
    network_relevant: true,
    deductible_relevant: false,
    oop_relevant: false,
    prescription_relevant: false,
    family_coverage_relevant: true,
    employer_sponsored_possible: true,
    medicare_related: false,
    medicaid_related: false,
    common_document_labels: ["vision plan", "vision benefits"],
    common_fields_expected: ["plan_name", "network_name", "family_plan_indicator", "plan_status"],
  },
  health_plan_generic: {
    health_plan_type_key: "health_plan_generic",
    display_name: "Health Plan",
    major_category: "generic_health",
    network_relevant: true,
    deductible_relevant: true,
    oop_relevant: true,
    prescription_relevant: true,
    family_coverage_relevant: true,
    employer_sponsored_possible: true,
    medicare_related: false,
    medicaid_related: false,
    common_document_labels: ["health plan", "member handbook", "benefits summary"],
    common_fields_expected: ["plan_name", "subscriber_name", "carrier_name", "plan_status"],
  },
};

export const HEALTH_PLAN_TYPE_KEYS = Object.freeze(Object.keys(HEALTH_PLAN_TYPE_REGISTRY));

export function listHealthPlanTypes() {
  return Object.values(HEALTH_PLAN_TYPE_REGISTRY);
}

export function getHealthPlanType(planTypeKey) {
  return HEALTH_PLAN_TYPE_REGISTRY[planTypeKey] || null;
}
