export const HEALTH_CARRIER_REGISTRY = {
  blue_cross_blue_shield_generic: {
    carrier_key: "blue_cross_blue_shield_generic",
    display_name: "Blue Cross Blue Shield",
    institution_type: "health_insurance_carrier",
    known_portal_urls: ["bcbs.com"],
    known_summary_of_benefits_labels: ["summary of benefits", "benefit highlights"],
    known_id_card_labels: ["member id", "rx bin", "group number"],
    known_deductible_labels: ["deductible", "annual deductible"],
    known_oop_labels: ["out-of-pocket maximum", "oop max"],
    known_network_labels: ["network", "provider network"],
    notes: "Generic BCBS starter profile covering regional plan families.",
  },
  anthem: {
    carrier_key: "anthem",
    display_name: "Anthem",
    institution_type: "health_insurance_carrier",
    known_portal_urls: ["anthem.com"],
    known_summary_of_benefits_labels: ["summary of benefits", "anthem benefits"],
    known_id_card_labels: ["member id", "plan code"],
    known_deductible_labels: ["deductible", "remaining deductible"],
    known_oop_labels: ["out-of-pocket maximum"],
    known_network_labels: ["anthem network", "ppo", "hmo"],
    notes: "Starter Anthem profile for commercial and employer coverage references.",
  },
  cigna: {
    carrier_key: "cigna",
    display_name: "Cigna",
    institution_type: "health_insurance_carrier",
    known_portal_urls: ["cigna.com"],
    known_summary_of_benefits_labels: ["summary of benefits", "coverage details"],
    known_id_card_labels: ["customer id", "group no"],
    known_deductible_labels: ["deductible", "family deductible"],
    known_oop_labels: ["out-of-pocket maximum"],
    known_network_labels: ["open access plus", "localplus"],
    notes: "Starter Cigna profile for commercial health coverage.",
  },
  aetna: {
    carrier_key: "aetna",
    display_name: "Aetna",
    institution_type: "health_insurance_carrier",
    known_portal_urls: ["aetna.com"],
    known_summary_of_benefits_labels: ["summary of benefits", "benefits overview"],
    known_id_card_labels: ["member id", "group number"],
    known_deductible_labels: ["deductible", "annual deductible"],
    known_oop_labels: ["out-of-pocket maximum"],
    known_network_labels: ["choice pos ii", "open choice ppo"],
    notes: "Starter Aetna profile.",
  },
  united_healthcare: {
    carrier_key: "united_healthcare",
    display_name: "UnitedHealthcare",
    institution_type: "health_insurance_carrier",
    known_portal_urls: ["uhc.com", "myuhc.com"],
    known_summary_of_benefits_labels: ["summary of benefits", "coverage summary"],
    known_id_card_labels: ["member id", "group number"],
    known_deductible_labels: ["deductible", "embedded deductible"],
    known_oop_labels: ["out-of-pocket limit"],
    known_network_labels: ["choice plus", "navigate", "network"],
    notes: "Starter UHC profile.",
  },
  kaiser_permanente: {
    carrier_key: "kaiser_permanente",
    display_name: "Kaiser Permanente",
    institution_type: "health_insurance_carrier",
    known_portal_urls: ["kp.org"],
    known_summary_of_benefits_labels: ["summary of benefits", "evidence of coverage"],
    known_id_card_labels: ["medical record number", "member id"],
    known_deductible_labels: ["deductible"],
    known_oop_labels: ["out-of-pocket maximum"],
    known_network_labels: ["kaiser permanente providers", "in-network only"],
    notes: "Integrated carrier/provider model with strong network relevance.",
  },
  humana: {
    carrier_key: "humana",
    display_name: "Humana",
    institution_type: "health_insurance_carrier",
    known_portal_urls: ["humana.com"],
    known_summary_of_benefits_labels: ["summary of benefits", "plan highlights"],
    known_id_card_labels: ["member id", "subscriber id"],
    known_deductible_labels: ["deductible"],
    known_oop_labels: ["maximum out-of-pocket"],
    known_network_labels: ["network", "ppo", "hmo"],
    notes: "Starter Humana profile across commercial and Medicare references.",
  },
  molina: {
    carrier_key: "molina",
    display_name: "Molina Healthcare",
    institution_type: "health_insurance_carrier",
    known_portal_urls: ["molinahealthcare.com"],
    known_summary_of_benefits_labels: ["member handbook", "benefits at a glance"],
    known_id_card_labels: ["member id"],
    known_deductible_labels: ["deductible"],
    known_oop_labels: ["out-of-pocket"],
    known_network_labels: ["provider directory", "network"],
    notes: "Starter profile for marketplace and Medicaid references.",
  },
  centene_reference: {
    carrier_key: "centene_reference",
    display_name: "Centene Reference",
    institution_type: "health_insurance_carrier",
    known_portal_urls: ["centene.com"],
    known_summary_of_benefits_labels: ["summary of benefits"],
    known_id_card_labels: ["member id"],
    known_deductible_labels: ["deductible"],
    known_oop_labels: ["out-of-pocket maximum"],
    known_network_labels: ["network"],
    notes: "Reference profile for Centene-affiliated plans.",
  },
  oscar: {
    carrier_key: "oscar",
    display_name: "Oscar",
    institution_type: "health_insurance_carrier",
    known_portal_urls: ["hioscar.com"],
    known_summary_of_benefits_labels: ["summary of benefits", "plan brochure"],
    known_id_card_labels: ["member id"],
    known_deductible_labels: ["deductible"],
    known_oop_labels: ["out-of-pocket maximum"],
    known_network_labels: ["network"],
    notes: "Starter marketplace-focused carrier profile.",
  },
  health_net: {
    carrier_key: "health_net",
    display_name: "Health Net",
    institution_type: "health_insurance_carrier",
    known_portal_urls: ["healthnet.com"],
    known_summary_of_benefits_labels: ["summary of benefits", "coverage facts"],
    known_id_card_labels: ["subscriber id", "group"],
    known_deductible_labels: ["deductible"],
    known_oop_labels: ["out of pocket maximum"],
    known_network_labels: ["network", "provider directory"],
    notes: "Starter Health Net profile.",
  },
  sharp_health_plan_reference: {
    carrier_key: "sharp_health_plan_reference",
    display_name: "Sharp Health Plan Reference",
    institution_type: "health_insurance_carrier",
    known_portal_urls: ["sharphealthplan.com"],
    known_summary_of_benefits_labels: ["summary of benefits"],
    known_id_card_labels: ["member id"],
    known_deductible_labels: ["deductible"],
    known_oop_labels: ["out-of-pocket maximum"],
    known_network_labels: ["network"],
    notes: "Regional reference profile.",
  },
  carrier_generic_health: {
    carrier_key: "carrier_generic_health",
    display_name: "Generic Health Carrier",
    institution_type: "health_insurance_carrier",
    known_portal_urls: [],
    known_summary_of_benefits_labels: ["summary of benefits", "benefit summary"],
    known_id_card_labels: ["member id", "group number"],
    known_deductible_labels: ["deductible"],
    known_oop_labels: ["out-of-pocket maximum"],
    known_network_labels: ["network"],
    notes: "Fallback profile for unknown or regional carriers.",
  },
};

export const HEALTH_CARRIER_KEYS = Object.freeze(Object.keys(HEALTH_CARRIER_REGISTRY));

export function listHealthCarriers() {
  return Object.values(HEALTH_CARRIER_REGISTRY);
}

export function getHealthCarrier(carrierKey) {
  return HEALTH_CARRIER_REGISTRY[carrierKey] || null;
}
