export function createEmptyNormalizedPolicy() {
  return {
    policy_identity: {
      carrier_name: "",
      product_name: "",
      policy_type: "",
      policy_number: "",
      issue_date: "",
      insured_name: "",
      owner_name: "",
      primary_beneficiary_name: "",
      contingent_beneficiary_name: "",
      beneficiary_status: "",
    },
    death_benefit: {
      death_benefit: null,
      initial_face_amount: null,
      current_death_benefit: null,
      minimum_death_benefit: null,
      option_type: "",
    },
    funding: {
      planned_premium: null,
      premium_paid_history: [],
      total_premium_paid: null,
      minimum_premium: null,
      guideline_premium_limit: null,
      mec_status: "",
    },
    values: {
      accumulation_value: null,
      cash_value: null,
      cash_surrender_value: null,
      indexed_account_value: null,
      fixed_account_value: null,
    },
    charges: {
      cost_of_insurance: null,
      admin_fee: null,
      monthly_deduction: null,
      expense_charge: null,
      rider_charge: null,
      total_policy_charges: null,
    },
    strategy: {
      current_index_strategy: "",
      allocation_percent: null,
      index_credit: null,
      crediting_rate: null,
      participation_rate: null,
      cap_rate: null,
      spread: null,
      floor_rate: null,
      multiplier: null,
      observed_statement_strategies: [],
      available_strategy_menu: false,
      strategy_source_evidence: "",
      strategy_menu_rows: [],
    },
    loans: {
      loan_balance: null,
      loan_interest: null,
      withdrawals: null,
      loan_activity: [],
    },
    riders: {
      detected_riders: [],
      rider_charge: null,
    },
    policy_timing: {
      statement_date: "",
      policy_year: null,
      insured_age: null,
    },
    extraction_meta: {
      document_types_seen: [],
      coverage_summary: {},
      missing_sections: [],
      carrier_confidence: "low",
      product_confidence: "low",
      statement_processing_order: [],
      newest_statement_selected: null,
    },
  };
}
